# .github/ISSUE_TEMPLATE/config.yml

# Main configuration for issue templates
name: MangoDriver Pro Issue Templates
description: |
  Use these templates to report issues or suggest features.
  Please choose the appropriate template to help us address your request efficiently.
title: "[TYPE] Issue Title"
labels: ["needs-triage"]
assignees: ["ashikurrahaman48"]

# Template chooser configuration
blank_issues_enabled: false

contact_links:
  - name: "🐛 Bug Report"
    url: "https://github.com/ashikurrahaman48/Mango-Driver-Pro/issues/new?template=bug_report.md&labels=bug,needs-triage"
    about: "Report a technical issue or unexpected behavior in MangoDriver Pro"
    
  - name: "✨ Feature Request" 
    url: "https://github.com/ashikurrahaman48/Mango-Driver-Pro/issues/new?template=feature_request.md&labels=enhancement,needs-review"
    about: "Suggest an enhancement or new functionality for MangoDriver Pro"
    
  - name: "🔒 Security Vulnerability"
    url: "https://github.com/ashikurrahaman48/Mango-Driver-Pro/security/policy"
    about: "Privately report security concerns (please don't disclose publicly)"

# Template-specific default settings
defaults:
  bug_report:
    title: "[BUG] "
    labels: ["bug", "needs-triage"]
    assignees: ["ashikurrahaman48"]
    
  feature_request:
    title: "[FEATURE] "
    labels: ["enhancement", "needs-review"] 
    assignees: ["ashikurrahaman48"]

# Localization support
locales:
  en:
    blank_issues_enabled: false
    description: "English language issue templates"
    
  bn:
    blank_issues_enabled: false
    description: "বাংলা ভাষার ইস্যু টেমপ্লেট"
