# .github/ISSUE_TEMPLATE/config.yml

# Disable blank issue creation
blank_issues_enabled: false

# Template selection options
contact_links:
  - name: "ЁЯРЫ ржмрж╛ржЧ рж░рж┐ржкрзЛрж░рзНржЯ ржХрж░рзБржи (Report Bug)"
    url: "https://github.com/ashikurrahaman48/Mango-Driver-Pro/issues/new?template=bug_report.md"
    about: "ржкрзНрж░ржпрзБржХрзНрждрж┐ржЧржд рж╕ржорж╕рзНржпрж╛ ржмрж╛ ржЕржкрзНрж░рждрзНржпрж╛рж╢рж┐ржд ржЖржЪрж░ржг рж░рж┐ржкрзЛрж░рзНржЯ ржХрж░рзБржи | Report technical issues"
    
  - name: "тЬи ржирждрзБржи ржлрж┐ржЪрж╛рж░ ржЕржирзБрж░рзЛржз (Request Feature)"
    url: "https://github.com/ashikurrahaman48/Mango-Driver-Pro/issues/new?template=feature_request.md"
    about: "ржирждрзБржи ржлрж╛ржВрж╢ржирж╛рж▓рж┐ржЯрж┐ ржмрж╛ ржЙржирзНржиржпрж╝ржирзЗрж░ ржкрж░рж╛ржорж░рзНрж╢ ржжрж┐ржи | Suggest enhancements"
    
  - name: "ЁЯФТ ржирж┐рж░рж╛ржкрждрзНрждрж╛ рж╕ржорж╕рзНржпрж╛ (Security Issue)"
    url: "https://github.com/ashikurrahaman48/Mango-Driver-Pro/security/policy"
    about: "ржирж┐рж░рж╛ржкрждрзНрждрж╛ ржЭрзБржБржХрж┐ ржЧрзЛржкржирзАржпрж╝ржнрж╛ржмрзЗ рж░рж┐ржкрзЛрж░рзНржЯ ржХрж░рзБржи | Privately report vulnerabilities"
