name: "Mark and Close Stale Issues/PRs"
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # General configuration
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: "This issue has been inactive for 60 days. It will be closed in 14 days unless there's new activity. Please comment or update to keep it open."
          stale-pr-message: "This pull request has been inactive for 60 days. It will be closed in 14 days unless there's new activity. Please comment or update to keep it open."
          close-issue-message: "This issue was closed due to inactivity. If you believe this is still relevant, please reopen or create a new issue."
          close-pr-message: "This pull request was closed due to inactivity. If you'd like to continue working on it, please reopen it."

          # Issue-specific configuration
          stale-issue-label: "stale"
          exempt-issue-labels: "priority:high, bug, security, roadmap"
          only-issue-labels: "" # Applies to all issues by default

          # PR-specific configuration
          stale-pr-label: "stale"
          exempt-pr-labels: "priority:high, WIP, blocked, needs-review"
          only-pr-labels: "" # Applies to all PRs by default

          # Repository-specific settings
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 100
          remove-stale-when-updated: true
          debug-only: false # Set to true for testing without actual changes

          # Customization for your project
          exempt-milestones: "Future Release, Backlog"
          exempt-assignees: true # Issues/PRs with assignees won't be marked stale
          exempt-draft-pr: true # Draft PRs won't be marked stale
